postcss/postcss-import

- test/fixtures/imports/relative/import.css
- test/index.js
This PR adds a test that fails. I found that it could be a `resolve` package issue, so that's why I do that. It's a start.
I found that the problem appears (at least) when a path starts with `../` because `resolve` doesn't use `paths` array in that case, it tries to resolve with `basedir` and fails.
Try replacing this test in `lib/sync.js` from `resolve` package (line 21-29):
```javascript
if (/^(?:\.\.?(?:\/|$)|\/|([A-Za-z]:)?[\\\/])/.test(x)) {
var res = y;
for (var i = opts.paths.length - 1; i >= 0; i--) {
if (path.resolve(y, opts.paths[i])) {
res = path.resolve(y, opts.paths[i]);
break;
}
};
res = path.resolve(res, x);
if (x === '..') res += '/';
var m = loadAsFileSync(res) || loadAsDirectorySync(res);
if (m) return m;
} else {
var n = loadNodeModulesSync(x, y);
if (n) return n;
}
``` …
> Add a test for relative import without from option

- index.js
- test/index.js
It fixes #22, but as there is no comment, I don't know why you try to clone `before` with `\n\n`
> Create `before` property on `first` element, only if defined

- index.js
- test/index.js
(fix #21 when `parent` is undefined)
> Properly clone nodes in `ignoredAtRules`

- README.md
- index.js
- package.json
- test/fixtures/glob.css
- test/fixtures/glob.expected.css
- test/fixtures/imports/glob-missing.css
- test/index.js
Added the `glob` option, defaulting to `false`, as suggested by @MoOx:
https://github.com/postcss/postcss-import/issues/8#issuecomment-57976207
Also added a couple tests and updated the README.md.
> Add glob option (Boolean, with default false). Closes gh-8

- index.js
- test/fixtures/glob-alt.css
- test/fixtures/glob-alt.expected.css
- test/index.js
Sorry, my previous PR only accounted for @import rules with double quotes. This commit ensures that globs work when the @import uses single quotes and/or the url(path) syntax. Added a test for it, too.
> Ensure glob works when using single quotes and/or url(path)

- index.js
- test/fixtures/glob.css
- test/fixtures/glob.expected.css
- test/index.js
Concatenated `moduleDirectories` to paths for globbed @import rules and modified the glob test to make sure it works. Wish I had noticed this the first time around. Anyway, this PR should be the last for the glob option. Thanks for merging these in so quickly. Really appreciate it!
> Make globbed imports work for module directories, too.

- index.js
> Prevent mutability issue, round 2

- README.md
- index.js
- package.json
- test/fixtures/imports/bar-decl.css
- test/fixtures/imports/foo-decl.css
- test/fixtures/plugins.css
- test/fixtures/plugins.expected.css
- test/index.js
Fixes #45
Willing to rename this option to something else, but I would appreciate your code review, @MoOx. I think I still need to write one more test that verifies warnings are being displayed for plugins applied on import.
> Introduce "plugins" option

- README.md
The `Default` part to the plugins option was on the same line as the Type. Simple fix here.
> Fix plugins section of README

- index.js
In reference to https://github.com/postcss/postcss-import/pull/55#issuecomment-113618351:
@MoOx you're right! I was getting warnings like this:
```
page2.css postcss-bem-linter: styles\blocks\block-bar.css:11:5: Invalid component
selector ".block-bar__element" [cssnext]
```
But this PR gives me much better warnings, like the following:
```
page2.css
11:5    Invalid component selector ".block-bar__element" [postcss-bem-linter]
```
Not quite sure how to add the proper tests, but I thought you could at least use a little help here.
> Fix warnings

- index.js
- package.json
This seemingly innocent operation is apparently responsible for
some serious performance bottlenecks. In testing, I've seen that
performance degrades by nearly an order of magnitute per file
imported. By not cloning options, this bottleneck goes away,
making this plugin significantly faster.
On a project with 9 `@import` rules running this plugin took on
average 7 seconds; by removing this clone operation it now takes
on average 100ms, with roughly 90% of that time spent in file I/O.
> Stop cloning options for a massive performance boost

- CHANGELOG.md
- README.md
- index.js
- lib/resolve-id.js
- test/fixtures/custom-resolve-array.css
- test/fixtures/custom-resolve-array.expected.css
- test/fixtures/imports/custom-array-1.css
- test/fixtures/imports/custom-array-2.css
- test/import.js
A bit more code but I'd like to move glob responsibility on resolve-id
> Add array of resolved files support

- test/fixtures/glob-alt.css
- test/fixtures/glob-alt.expected.css
- test/glob.js
resolver response for globs. They use the same parser as regular uris
> Remove unnecessary glob-alt test

- CHANGELOG.md
- README.md
- lib/resolve-id.js
- package.json
- test/glob.js
`moduleDirectories` shound't be used caz they do not give any resolving benefits and can just confuse. Better give ability to add it to path.
Also all resolvings should be consistent with enabled `glob`, so non-glob imports should also be resolved as glob.
> Simple glob resolver

- CHANGELOG.md
- index.js
- package.json
- test/fixtures/imports/inline-comment.scss
- test/fixtures/scss-parser.css
- test/fixtures/scss-parser.expected.css
- test/fixtures/scss-syntax.css
- test/fixtures/scss-syntax.expected.css
- test/plugins.js
> Add custom syntax and parser support

- index.js
- lib/parse-statements.js
Now parseStatements returns also `nodes` and `media` types.
In parseStyles I just filter them out. I will use and test them in the next PR.
Everything to make correct async behaviour.
> Statements

- lib/parse-statements.js
- test/lint.js
> Skip comments between imports

- package.json
Add @empty statements for load-content and resolve-id so that their deps aren't loaded in browser environment. This allows for JSPM to not error out. Custom resolve/load functions will need to be provided as options for proper functionality.
(New PR cuz I'm a terrible Git wizard and failed to squash properly after a few attempts.)
> Add JSPM browser field

- lib/resolve-id.js
> Improved tolerancy for failed imports of jspm-chain. See issue #198. Works around https://github.com/jspm/jspm-cli/pull/1779 stuntil that is fixed.

- test/fixtures/imports/foo-first.css
- test/fixtures/imports/foo-second.css
- test/fixtures/order.css
- test/fixtures/order.expected.css
- test/order.js
From https://github.com/postcss/postcss-import/issues/168
> Add test for nested import ordering

- index.js
- package.json
- test/order.js
- test/plugins.js
Had to edit a test that depended on the old, incorrect behavior.
Fixes #168 :tada:
> Nested import ordering

- README.md
> - **This plugin attempts to follow the CSS `@import` spec**; `@import` statements must precede all other statements (besides `@charset`).
@MoOx Is this clear enough?
Fixes https://github.com/postcss/postcss-import/issues/227.
> Make a note in the README about putting `@import`s first

- lib/parse-statements.js
- test/lint.js
Fixes #176 
@MoOx How does this look?
> Warn about all @imports after other CSS declarations

- README.md
- package.json
Users can still install it manually if they need the functionality.
Fixes https://github.com/postcss/postcss-import/issues/212.
@MoOx Do the docs look good?
Note that this PR is against the `v9-dev` branch, not `master`. All future PRs aimed for v9 should be made against that branch.
> BREAKING: Remove pkg-resolve as a dep

- index.js
- test/import.js
Fixes https://github.com/postcss/postcss-import/issues/192.
@MoOx What do you think of this? Is there some other case that we can test for a readable stack trace, since file not found is now an error?
> BREAKING: File not found is an Error, not a Warning

- README.md
- index.js
- test/custom-resolve.js
Use default resolver when custom resolve does not return an absolute path.
Resolves https://github.com/postcss/postcss-import/issues/216. (No pun intended :smile_cat: )
@ai Does this look good?
> Change resolve behavior

- index.js
- lib/process-content.js
- package.json
- test/custom-syntax-parser.js
- test/fixtures/import-css-sss.expected.css
- test/fixtures/import-css-sss.sss
- test/fixtures/import-sss-css.css
- test/fixtures/import-sss-css.expected.css
- test/fixtures/import-sss.css
- test/fixtures/import-sss.expected.css
- test/fixtures/imports/foo-recursive.sss
- test/fixtures/imports/import-sugarbar.css
- test/fixtures/imports/sugarbar.sss
- test/fixtures/sugar-import-css.expected.css
- test/fixtures/sugar-import-css.sss
- test/fixtures/sugar.expected.css
- test/fixtures/sugar.sss
- test/helpers/compare-fixtures-ext.js
- test/plugins.js
This is still a WIP. Will most likely need rebased when I'm done.
---
_Warning: This is a weird approach to solving this problem._
Perhaps this approach is naive; but it should be pretty well bulletproof. It is based on the (correct :stuck_out_tongue: ) assumption that if a parser can parse the input, it is the correct parser.
If the file is `.sss`, it tries that parser first. For all other files (or if SugarSS parsing fails) it tries the user-passed parser (if available). If that fails, it tries the default parser.
The reason I chose this approach is that we have no reliable way of telling if `result.opts.parser` is a CSS-compliant parser. See https://github.com/postcss/postcss-import/issues/242 for more background.
The main problem with this approach is error handling/reporting. …
> Play well with Custom Syntax

- index.js
- test/import-events.js
@ai Not sure if this is done right.
> Add warning message for deprecated addDependencyTo option

- README.md
- index.js
- lib/resolve-id.js
- test/fixtures/resolve-custom-modules.css
- test/fixtures/resolve-custom-modules.expected.css
- test/resolve.js
- test/shared_modules/shared-auto/index.css
- test/shared_modules/shared-by-hand/style.css
- test/shared_modules/shared-dep/index.css
- test/shared_modules/shared-fake/main.css
- test/shared_modules/shared-fake/package.json
- test/shared_modules/shared-nest/index.css
- test/shared_modules/shared-nest/shared_modules/shared-ed/index.css
- test/shared_modules/shared-use-dep-too/index.css
- test/shared_modules/shared-use-dep/index.css
Allows appending to the default list of modules directories. I picked a name that I think sounds good, but happy to change it if y'all have something else you'd prefer. 😄 
Relevant discussion: https://github.com/postcss/postcss-import/issues/195
@RyanZim
> Add `addModulesDirectories` config

- index.js
- package.json
- Resolves #275
- Removes any-promise subdependency
- Removes runtime assert from promise-each
> Remove promise-each dependency

- .travis.yml
- appveyor.yml
- index.js
- lib/parse-statements.js
- lib/process-content.js
- lib/resolve-id.js
- package.json
- test/custom-load.js
- test/custom-resolve.js
- test/custom-syntax-parser.js
- test/fixtures/resolve-cwd.css
- test/fixtures/resolve-local-modules.css
- test/helpers/compare-fixtures-ext.js
- test/helpers/compare-fixtures.js
- test/import-events.js
- test/import.js
- test/lint.js
- test/media.js
- test/order.js
- test/plugins.js
- test/resolve.js
- test/sourcemap/out.css.map
This PR updates PostCSS 6 and all dependencies. It is divided into separate commits, all of which individually pass testing.
- Updates PostCSS 6, which requires changes to .travis.yml and appveyor.yml
- Updates eslint, which requires changes to most test scripts to meet eslint-config-i-am-meticulous requirements
- Updates sugarss, no troubles
- Updates AVA, which requires updates to most tests as the current directory is now the package directory (see avajs/ava#1074)
_Note: eslint did require removing the jspmResolve oddity._
> Use PostCSS 6

- package.json
because `prettier-eslint-cli` mistakenly published breaking change as a minor patch in v3 ([issue](https://github.com/prettier/prettier-eslint-cli/issues/67)) the ci tests fail. I changed `prettier-eslint-cli` to the latest version and fixed options in lint script to reflect the changes introduced in the new version.
> Fix linting options

- README.md
As far as I know, transform option is removed, isn't it? Or can I still use it only in this case?
> Remove transform option from README.md

- test/fixtures/resolve-npm-subpackages.css
- test/fixtures/resolve-npm-subpackages.expected.css
- test/node_modules/modularized-css/foo/boo/boomod.css
- test/node_modules/modularized-css/foo/index.css
- test/resolve.js
Added tests that show the ability of postcss-import to consume RxJS style subpackages.  In other words instead of consuming the entire kitchen sink via the `style` or `main` attribute, only consume a subpackage of the npm module.
> Added RxJS Style NPM packages and tests

- index.js
- test/import-events.js
This PR fixes #379. The lack of `plugin` property leads to a message mishandling by other plugins and may cause an issue described as the second problem in https://github.com/nodaguti/postcss-calc-warning.
> Set plugin property to dependency messages which is required according to the API doc

- index.js
- lib/parse-statements.js
- test/fixtures/charset-error.css
- test/fixtures/charset-import.css
- test/fixtures/charset-import.expected.css
- test/fixtures/imports/charset.css
- test/import.js
- test/lint.js
OK, this is a _slightly_ naive implementation, but I think it's pretty good. If there's a `@charset` anywhere in the CSS, move it to the top of the output and apply it to everything. If there are multiple `@charset`s, compare them. If they're all the same, just use one. If they're different, there's no way we can put all of these in one file, so error out. If you legitimately need to import files with different charsets, you can use the `plugins` or `load` option to add logic to convert all your files to a single encoding that matches the entry point.
Also added checks to ensure that `@charset` comes first, warn the user if this isn't the case.
Technically a breaking change due to adding the error and warning cases.
Attn @SLKnutson
> Fix charset handling

- index.js
- lib/process-content.js
> remove postcss imports

- README.md
Fixes https://github.com/postcss/postcss-import/issues/463
Since this is a package used during development, and is not a package containing files that get published, it should be a dev dependency.
> Update installation instructions to save to devDependencies

- README.md
old link doesn't work in postcss8, substituted one that does
edit: DOESNT work
> updated glob link in README

- README.md
- index.js
- test/fixtures/imports/layer-anonymous.css
- test/fixtures/imports/layer-level-2-anonymous.css
- test/fixtures/imports/layer-level-2.css
- test/fixtures/imports/layer-level-3.css
- test/fixtures/imports/layer-rule-grouping.css
- test/fixtures/imports/layer.css
- test/fixtures/layer-import-atrules-anonymous.css
- test/fixtures/layer-import-atrules-anonymous.expected.css
- test/fixtures/layer-import-atrules.css
- test/fixtures/layer-import-atrules.expected.css
- test/fixtures/layer-rule-grouping.css
- test/fixtures/layer-rule-grouping.expected.css
- test/fixtures/layer.css
- test/fixtures/layer.expected.css
- test/layer.js
fixes : https://github.com/postcss/postcss-import/issues/495
@RyanZim it still feels a bit like the complexity (which I added) is exploding and the overal shape of the code base isn't optimal. But I also do not dislike this fix :)
Important spec bits : https://www.w3.org/TR/css-cascade-5/#at-import
> the optional layer keyword or layer() function assigns the contents of the style sheet into its own anonymous [cascade layer](https://www.w3.org/TR/css-cascade-5/#cascade-layers) or into the named cascade layer.
>
>The layer is added to the [layer order](https://www.w3.org/TR/css-cascade-5/#layer-ordering) even if the import fails to load the stylesheet, but is subject to any [import conditions](https://www.w3.org/TR/css-cascade-5/#import-conditions) (just as if declared by an …
> fix import with layer

- test/fixtures/duplicates.expected.css
- test/fixtures/layer-import-atrules-anonymous.expected.css
- test/fixtures/layer-import-atrules.expected.css
- test/fixtures/layer-rule-grouping.expected.css
- test/fixtures/layer.expected.css
- test/fixtures/no-duplicate.expected.css
same as https://github.com/postcss/postcss-import/pull/503 but in reverse
> update test results for PostCSS 8.4.19

- index.js
- lib/assign-layer-names.js
- test/fixtures/ignore.css
- test/fixtures/ignore.expected.css
- test/fixtures/imports/layer-level-2-anonymous.css
- test/fixtures/layer-import-atrules-anonymous.css
- test/fixtures/layer-import-atrules-anonymous.expected.css
fix : #510
- preserves `layer` when writing `@import` rules
- correctly "concats" layers for `@import` rules
@argyleink Can you also take a look at this?
> preserve `layer` in ignored `@imports` statements

- lib/join-media.js
- test/fixtures/filter-ignore.expected.css
- test/fixtures/ignore.expected.css
fix : #512
This will not help with :
`print and (min-width: 300px)` + `screen and (min-width: 300px)`
> correctly sort media queries before joining them

- index.js
- lib/data-url.js
- lib/load-content.js
- test/data-url.js
- test/fixtures/data-url.css
- test/fixtures/data-url.expected.css
- test/fixtures/imports/data-url.css
This change adds support for :
```css
@import url(data:text/css;base64,...)
```
_Before this change a data url would throw an error, so this is not something that is being used today by users of this plugin._
As far as I can tell the change required is minimal and everything just works.
- media queries
- at layer
- sourcemaps
- nesting multiple imports within data urls
---------
I don't this is useful on its own.
Authors should not be base64 encoding CSS source code and storing this in `@import` urls.
It can however be useful for other plugins that have non-standard interactions with `@import`.
Another plugin that does want to provide extra features can choose to store as base64 instead of inlining.
This keeps the source valid with all `@import` rules before anything else and all in the …
> add data url support

- README.md
fixes : https://github.com/postcss/postcss-import/issues/519
We got a question about this in the CSSTools discord.
It seems that people assume that `@import url()` is not supported because it isn't listed in the readme.
This change adds some simple examples.
> add docs for url notation

- lib/process-content.js
- package.json
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------|---------|----------|---------|---------|-------------------
All files               |   99.48 |    99.26 |     100 |   99.48 |                   
postcss-import         |     100 |      100 |     100 |     100 |                   
index.js              |     100 |      100 |     100 |     100 |                   
postcss-import/lib     |   98.87 |    98.49 |     100 |   98.87 |                   
assign-layer-names.js |     100 |      100 |     100 |     100 |                   
data-url.js           |     100 |      100 |     100 |     100 |                   
join-layer.js         |     100 |      100 |     100 |     100 |                   
join-media.js         |     100 | …
> add c8 test coverage

- index.js
- lib/data-url.js
- lib/parse-statements.js
- lib/parse-styles.js
- test/fixtures/data-url.css
- test/fixtures/data-url.expected.css
- add support for url encoded data urls
- fix handling of embedded relative imports
> extend and fix data url imports

- README.md
- lib/parse-styles.js
- lib/resolve-id.js
- test/import.js
- test/layer.js
- test/plugins.js
fixes https://github.com/postcss/postcss-import/issues/518
I've kept the `new Error()` when checking plugin options.
I don't think these are CSS syntax errors : https://github.com/postcss/postcss/blob/main/docs/guidelines/plugin.md#41-use-nodeerror-on-css-relevant-errors
> use `node.error` for CSS relevant errors

- README.md
- index.js
- lib/parse-styles.js
- test/helpers/check-fixture.js
- test/import.js
fixes : https://github.com/postcss/postcss-import/issues/84
> add `warnOnEmpty` plugin option

- lib/parse-styles.js
- test/data-url.js
- test/fixtures/data-url.css
- test/fixtures/data-url.expected.css
The current code prevents further inlining of embedded imports but it doesn't stop a browser from possible loading and applying it.
~~Adding `not all` has the intended effect.~~
Setting `stmt.children = []` prevents inlining and removes the `@import` statement.
> Error on embedded imports in data urls

- lib/parse-statements.js
- test/lint.js
This makes the parser for `@import` preludes a bit stricter.
> parser fixes and test coverage

- lib/parse-statements.js
- test/fixtures/filter-all.expected.css
- test/fixtures/filter-some.expected.css
- test/fixtures/ignore.expected.css
- test/fixtures/media-combine.expected.css
- test/fixtures/simple.css
- test/helpers/ast-checker.js
- test/helpers/check-fixture.js
fixes : https://github.com/postcss/postcss-import/issues/557
> ensure that media params remain string values

- lib/parse-styles.js
- test/fixtures/filter-ignore.css
- test/fixtures/filter-ignore.expected.css
- test/fixtures/imports/modules/subpath/a.css
- test/fixtures/imports/modules/subpath/package.json
- test/fixtures/imports/modules/subpath/style.css
- test/fixtures/subpath.css
- test/fixtures/subpath.expected.css
- test/resolve.js
The intention behind ignoring urls with a fragment was to make the plugin more correct.
The thinking at the time was that these are never valid imports for a filesystem.
With nodejs subpath imports that assumption is incorrect.
> Allow urls that contain fragments, fixes #560

- lib/apply-conditions.js
- lib/apply-styles.js
- lib/base64-encoded-import.js
- lib/parse-statements.js
- lib/parse-styles.js
- test/fixtures/imports/layer-followed-by-ignore.css
- test/fixtures/imports/layer-only.css
- test/fixtures/layer-followed-by-ignore-with-conditions.css
- test/fixtures/layer-followed-by-ignore-with-conditions.expected.css
- test/fixtures/layer-followed-by-ignore-without-conditions.css
- test/fixtures/layer-followed-by-ignore-without-conditions.expected.css
- test/fixtures/layer-followed-by-ignore.css
- test/fixtures/layer-followed-by-ignore.expected.css
- test/fixtures/layer-statement-with-conditions.css
- test/fixtures/layer-statement-with-conditions.expected.css
- test/layer.js
Fixes the original problem described in https://github.com/postcss/postcss-import/issues/567#issue-2596115833
The root cause is that all nodes are added to either the `imports` or `bundle` array in https://github.com/postcss/postcss-import/blob/d43ca1506d65d9943a3c4bb885aff94dc809d69c/lib/parse-styles.js#L36-L37
While `@layer` statements (those without a rule body) can precede `@import`.
To fix this issue I've added a new statement type for layers and added the needed mechanics to apply conditions to these. To express conditional `@layer` statements before other `@import` statements, or `@layer` statements that end up in between other `@import` statements we use base64 encoded stylesheets:
`@import 'data:text/css;base64,QGxheWVyIGxheWVyLWJldGE=' print;` is equivalent to `@media print { …
> Fix incorrect cascade layer order when some resources can not be inlined
