postcss/postcss-import

index.js

add match for souce object

---

index.js

Similar to this https://github.com/borodean/postcss-assets/issues/6
Reference: https://github.com/postcss/postcss-plugin-boilerplate

Use common PostCSS plugin API

---

README.md
index.js

I updated `index.js` and `README.md`. I didn't add any new tests though, since it looks like the conditions already tested for `node_modules` perfectly satisfy `bower_components` too.
Cheers!

Added support for Bower packages (resolves #65)

---

index.js

Simplify root node path

---

.eslintrc
package.json

I can't do `npm i something -D` without changing default package.json codestyle. Also yaml seems much prettier.

Use eslintrc for simple package.json updating

---

index.js

Reduce options assigning

---

lib/parse-imports.js
test/lint.js

Close https://github.com/postcss/postcss-import/issues/133

Follow @import spec

---

README.md

Fix a syntax error in README.md

---

README.md

Fix type declaration and description. Provide usage example with postcss-loader

Change docs of `addDependencyTo` option

---

README.md

I got a bit confused and tried to return just a Promise before checking the tests and realising it expects a resolved Promise:
``` js
transform(css) {
return postcss([aPlugin]).process(css); // didn't work
}
```
I've added a note to make it clearer

Add clarification on Promise usage in transform

---

README.md

Missing comma in configuration example.
Thank you!

Add missing comma to README.md example

---

README.md

:pencil2: `it will looks` :arrow_right: `it will look`
Thank you!

📝 Fix Grammatical Error

---

package.json

Fixes https://github.com/postcss/postcss-import/issues/212.

Make pkg-resolve an optional dep

---

index.js
test/import-events.js

Resolves #233.
@MoOx @ai Review?

Add dependency message support

---

README.md

Will merge in a few days if there are no objections.

Add docs for dependency message

---

.travis.yml
package.json

This aligns the minimum Node.js version with PostCSS 7

Use PostCSS 7 & drop support for Node.js 4

---

package.json

Update prettier to version 1.14.0

---

package.json

Fixes https://github.com/postcss/postcss-import/issues/394

Update eslint-plugin-import to version 2.17.1

---

package.json

Update prettier to version 1.19.1

---

index.js
test/fixtures/imports/charset-content.css
test/fixtures/media-charset.css
test/fixtures/media-charset.expected.css
test/media.js

Fix handling of @charset in media imports

---

.github/workflows/ci.yaml
package.json

As per https://github.com/postcss/postcss-import/pull/496#issuecomment-1232092878

BREAKING: Require Node v14+

---

README.md

fixes : https://github.com/postcss/postcss-import/issues/516

link to postcss-import-url plugin

---

lib/parse-styles.js

removes a single trailing space.

formatting

---

.github/workflows/ci.yaml
package.json

BREAKING: Require Node v18+
